name: ansu_ui
description: A new Flutter package.
version: 0.0.4
author:

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.0.0
  flutter_easyrefresh:
    git:
      url: https://github.com/xuelongqy/flutter_easyrefresh
      ref: v2
  lpinyin: ^2.0.1
  image_picker: ^0.7.2
  bot_toast: ^4.0.0+1
  velocity_x: ^2.6.1
  expandable: ^5.0.1
  animated_collection:
    git:
      url: http://159.75.73.143:8080/laiiihz/animated_collection.git
  get: ^4.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
