name: ansu_ui
description: A new Flutter package.
version: 0.0.4
author:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.0.0-nullsafety.7
  flutter_easyrefresh: ^2.1.8
  lpinyin: ^1.1.1
  image_picker: ^0.7.2
  bot_toast: ^4.0.0+1
  velocity_x:
    git:
      url: http://test.akuhotel.com:8099/aku_fe/velocityX.git
      branch: stable
  expandable: ^4.1.4
  animated_collection:
    git:
      url: http://test.akuhotel.com:8099/aku_fe/animated_collection.git
  get:

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
