name: ansu_ui
description: A new Flutter package.
version: 0.0.4
author:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_screenutil: ^3.2.0
  flutter_easyrefresh: ^2.1.6
  lpinyin: ^1.1.0
  image_picker: ^0.6.7+15
  bot_toast: ^3.0.5
  velocity_x:
  expandable: ^4.1.4
  aku_ui:
    git:
      url: http://test.akuhotel.com:8099/aku_fe/aku_ui.git

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
